<a href="https://colab.research.google.com/github/minhhoang258/LeDinhHoangMinh20104043/blob/main/BU%E1%BB%94I%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
BUỔI 5

In [2]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test = [[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

Do chinh xac 1.0
[0 1 0 1]


In [5]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test=[[0,0],[0,1],[1,0],[1,1]]
y_test=model.predict(x_test)
print(y_test)

Do chinh xac 0.5
[0 0 0 0]


In [7]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
dulieu = pd.read_csv('/content/hehe.csv')
A = dulieu.drop(['speies','sex'],axis =1)
C = dulieu[(dulieu['speies']=='B') & (dulieu['sex']=='M')]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))


do chinh xac 0.5


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = '/content/hehe.csv'
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train, y_train)
print("Accuracy: ", model.score(x_train,y_train))
x_i = [[7.2,7.7,14.3,18,7],[8,7.9,15.3,16.1,7]]
y_p = model.predict(x_i)
print(y_p)

Accuracy:  0.8571428571428571
[0 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
import pandas as pd
from sklearn.model_selection import train_test_split
data = (pd.read_csv('/content/iris.csv'))
x = data.drop(['variety'],axis=1)
y = data['variety'].replace(['Versicolor','Setosa','Virginica'],[2,1,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
model = Perceptron()
model.fit(x,y)
x_i = [[5.5,3.6,2.4,1.6],[4.6,3.9,2.2,1.4],[5,6,3,5]]
y_p = model.predict(x_i)
print('Accuracy',model.score(x,y))
print(y_p)

Accuracy 0.8933333333333333
[1 1 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
